language: node_js

node_js:
  - "lts/*"

cache: npm

# addons:
#   sonarqube: true

git:
  depth: false

before_script:
  - npm run test-ts-decls
  - npm install

script:
  - npm run check
  - npm run test
  - BUILD_BRANCH=$TRAVIS_BRANCH BUILD_COMMIT=$TRAVIS_COMMIT npm run build

# after_success:
#   - bash sonar-scanner.sh

deploy:
  - provider: s3
    access_key_id: ${AWS_ACCESS_KEY_ID_STAGE}
    secret_access_key: ${AWS_SECRET_ACCESS_KEY_STAGE}
    bucket: aws-development-split-public
    region: us-east-1
    local_dir: ${TRAVIS_BUILD_DIR}/umd
    upload-dir: sdk
    skip_cleanup: true
    acl: public_read
    cache_control: "max-age=31536000, public"
    on:
      branch: localhost_mode_export
  - provider: s3
    access_key_id: ${AWS_ACCESS_KEY_ID_PROD}
    secret_access_key: ${AWS_SECRET_ACCESS_PROD}
    bucket: split-public
    region: us-east-1
    local_dir: ${TRAVIS_BUILD_DIR}/umd
    upload-dir: sdk
    skip_cleanup: true
    acl: public_read
    cache_control: "max-age=31536000, public"
    on:
      branch: main
