name: ci-cd
on:
  pull_request:
    branches:
      - main
      - development
  push:
    branches:
      - '*'

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'push' && github.run_number || github.event.pull_request.number }}
  cancel-in-progress: true

permissions:
  contents: read
  id-token: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: npm ci
        run: npm ci

      - name: npm test-ts-decls
        run: npm run test-ts-decls

      - name: npm check
        run: npm run check

      - name: npm test
        run: npm run test

      - name: npm build
        run: BUILD_BRANCH=$(echo "${GITHUB_REF#refs/heads/}") npm run build

      - name: Store assets
        if: ${{ github.event_name == 'push' && (github.ref == 'refs/heads/rb_segments_and_prerequisites' || github.ref == 'refs/heads/main') }}
        uses: actions/upload-artifact@v4
        with:
          name: assets
          path: umd/
          retention-days: 1

  upload-stage:
    name: Upload assets
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/rb_segments_and_prerequisites' }}
    strategy:
      matrix:
        environment:
          - stage
          # - stage-eu
        include:
          - environment: stage
            account_id: "079419646996"
            bucket: split-public-stage
          # - environment: stage-eu
            # account_id: "901851837056"
            # bucket: split-public-stage-eu-west-1

    steps:
      - name: Download assets
        uses: actions/download-artifact@v4
        with:
          name: assets
          path: umd

      - name: Display structure of assets
        run: ls -R
        working-directory: umd

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ matrix.account_id }}:role/gha-public-assets-role
          aws-region: us-east-1

      - name: Upload to S3
        run: aws s3 sync $SOURCE_DIR s3://$BUCKET/$DEST_DIR $ARGS
        env:
          BUCKET: ${{ matrix.bucket }}
          SOURCE_DIR: ./umd
          DEST_DIR: sdk
          ARGS: --acl public-read --follow-symlinks --cache-control max-age=31536000,public

  upload-prod:
    name: Upload assets
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    strategy:
      matrix:
        environment:
          - prod
          # - prod-eu
        include:
          - environment: prod
            account_id: "825951051969"
            bucket: split-public
          # - environment: prod-eu
            # account_id: "842946900133"
            # bucket: split-public-eu-west-1

    steps:
      - name: Download assets
        uses: actions/download-artifact@v4
        with:
          name: assets
          path: umd

      - name: Display structure of assets
        run: ls -R
        working-directory: umd

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ matrix.account_id }}:role/gha-public-assets-role
          aws-region: us-east-1

      - name: Upload to S3
        run: aws s3 sync $SOURCE_DIR s3://$BUCKET/$DEST_DIR $ARGS
        env:
          BUCKET: ${{ matrix.bucket }}
          SOURCE_DIR: ./umd
          DEST_DIR: sdk
          ARGS: --acl public-read --follow-symlinks --cache-control max-age=31536000,public
