name: ci-cd
on:
  pull_request:
    branches:
      - main
      - development
  push:
    branches:
      - '*'

permissions:
  contents: read
  id-token: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up nodejs
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'

      - name: npm CI
        run: npm ci

      - name: npm ts tests
        run: npm run test-ts-decls

      - name: npm Check
        run: npm run check

      - name: npm Test
        run: npm run test

      - name: npm Build
        run: BUILD_BRANCH=$(echo "${GITHUB_REF#refs/heads/}") BUILD_COMMIT=${{ github.sha }} npm run build

      - name: Configure AWS credentials (development)
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/ga_auto_require' }}
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::079419646996:role/public-assets
          aws-region: us-east-1

      - name: Upload to S3 (development)
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/ga_auto_require' }}
        run: aws s3 sync $SOURCE_DIR s3://$BUCKET/$DEST_DIR $ARGS
        env:
          BUCKET: split-public-stage
          SOURCE_DIR: ./umd
          DEST_DIR: sdk
          ARGS: --acl public-read --follow-symlinks --cache-control max-age=31536000,public

      - name: Configure AWS credentials (main)
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::825951051969:role/public-assets
          aws-region: us-east-1

      - name: Upload to S3 (main)
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: aws s3 sync $SOURCE_DIR s3://$BUCKET/$DEST_DIR $ARGS
        env:
          BUCKET: split-public
          SOURCE_DIR: ./umd
          DEST_DIR: sdk
          ARGS: --acl public-read --follow-symlinks --cache-control max-age=31536000,public
